cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

finesauces_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('users.urls')),

    path('', include('listings.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('<slug:category_slug>', views.product_list,
         name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', views.product_detail,
         name='product_detail'),
    path('search/', views.search_list, name="search"),
    path('', views.product_list, name='product_list'),
]

orders/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required
from finesauces_project.decorators import user_created_order

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/pdf/',
         staff_member_required(views.invoice_pdf), name='invoice_pdf'),
    path('order/<int:order_id>/pdf/',
         user_created_order(views.invoice_pdf), name='customer_invoice_pdf'),
    path('order/<int:order_id>/',
         user_created_order(views.order_detail), name='order_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.forms import NumberInput


class CartAddProductForm(forms.Form):

    quantity = forms.IntegerField(
        min_value=1,
        widget=NumberInput(attrs={
            'class': 'form-control text-center px-3',
            'value': 1
        }))

    CHOICES = (
        (35, 35),
        (36, 36),
        (37, 37),
        (38, 38),
        (39, 39),
        (40, 40),
        (41, 41),
        (42, 42),
        (43, 43),
    )
    size = forms.IntegerField(
        widget=forms.Select(
            choices=CHOICES,
            attrs={'style': "border: none; margin-left: 1.5rem;"}
        ),

    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings

from listings.models import Product
from .forms import CartAddProductForm
from decimal import Decimal


def get_cart(request):

    cart = request.session.get(settings.CART_ID)
    if not cart:
        cart = request.session[settings.CART_ID] = {}
    return cart


def cart_add(request, product_id):
    cart = get_cart(request)
    product = get_object_or_404(Product, id=product_id)
    product_id = str(product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data

        if product_id not in cart:
            cart[product_id] = {
                'quantity': 0,
                'size': 0,
                'price': str(product.price)
            }
        if request.POST.get('overwrite_gty'):
            cart[product_id]['quantity'] = cd['quantity']
            print("if")
        else:
            cart[product_id]['quantity'] += cd['quantity']

        if request.POST.get('overchoice_gty'):
            cart[product_id]['size'] = cd['size']
        else:
            cart[product_id]['size'] = cd['size']

        request.session.modified = True
        return redirect('cart:cart_detail')


def cart_detail(request):
    cart = get_cart(request)
    product_ids = cart.keys()
    products = Product.objects.filter(id__in=product_ids)
    temp_cart = cart.copy()

    for product in products:
        cart_item = temp_cart[str(product.id)]
        cart_item['product'] = product
        cart_item['total_price'] = (
            Decimal(cart_item['price']) * cart_item['quantity'])
        cart_item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': cart_item['quantity']
        })
        cart_item['update_size_form'] = CartAddProductForm(initial={
            'size': cart_item['size']
        })
    cart_total_price = sum(
        Decimal(item['price']) * item['quantity'] for item in temp_cart.values())

    return render(request, 'cart/detail.html',
                  {
                      'cart': temp_cart.values(),
                      'cart_total_price': cart_total_price
                  }
                  )


def cart_remove(request, product_id):

    cart = get_cart(request)
    product_id = str(product_id)
    if product_id in cart:
        del cart[product_id]

        request.session.modified = True

        return redirect('cart:cart_detail')


def cart_clear(request):
    del request.session[settings.CART_ID]

templates/cart/detail.html
{% extends 'base.html' %}
{% block title %}Shopping cart{% endblock %}
{% block content %}
<div class="card shadow-custom border-0 col-lg-12 mx-auto mb-3">
    <h3 class="py-2 font-weight-bold text-grey text-center">
        Ваши заказы:
    </h3>
    <div class="row justify-content-center py-2 text-center header-desc">
        <div class="col-lg-2 align-self-center">
            Продукт
        </div>
        <div class="col-lg-2 align-self-center">
            Описание
        </div>
        <div class="col-lg-2 align-self-center">
            Размер
        </div>
        <div class="col-lg-1 align-self-center">
            Цена
        </div>
        <div class="col-lg-2 align-self-center">
            Количество
        </div>
        <div class="col-lg-3 align-self-center">
          Итоговая цена
        </div>
    </div>
    <hr class="mt-0">
    {% for item in cart %}
        {% with product=item.product %}
            <div class="row justify-content-center cart">
                <div class="cart-item col-4 col-lg-2">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" alt=""
                        class="img-fluid rounded-0">
                    </a> 
                </div>
            <div class="cart-item product-name col-12 col-lg-2 align-self-center text-center">
                {{ product.name }}
            </div>
            <div class="cart-item col-12 col-lg-2 align-self-center">
      <form action="{% url 'cart:cart_add' product.id %}" method="POST">  
                  <div class="text-green mb-0 text-center dfd" style="
                    display: flex;
                    flex-direction: row;
                    /* justify-content: space-around; */
                    gap: 2.7rem;
                    height: 2.4rem;
                    border: 2px solid #D9D9D9; border-radius: 50px">
                    <input type="hidden" name="overchoice_gty" value="True">
                    {{ item.update_size_form.size }}
                      <button type="submit" class="btn text-orange"
                        data-toggle="tooltip" data-placement="top"
                        title="Обновить" style="background: #fcae2c; border-radius: 0 50px 50px 0">
                        <i class="fas fa-edit" style="color: #ffffff;"></i>
                      </button>
                  </div>
            </div>
    <div class="cart-item col-12 col-sm-3
      col-lg-1 align-self-center text-center">
      <span>₽{{ product.price }}</span>
    </div>
    <div class="cart-item col-6 col-sm-5 col-lg-2 align-self-center">
      
        {% csrf_token %}
        <span class="input-group shopping-cart">
            {{ item.update_quantity_form.quantity }}
          <input type="hidden" name="overwrite_gty" value="True">
          <div class="input-group-append">
            <button type="submit" class="btn text-white"
              data-toggle="tooltip" data-placement="top"
              title="Обновить">
              <i class="fas fa-edit"></i>
            </button>
          </div>
        </span>
      </form>
    </div>
    <div class="cart-item col-12 col-sm-3
      col-lg-2 align-self-center text-right">
      <span>₽{{ item.total_price }}</span>
    </div>
    <div class="cart-item col-12 col-lg-1 text-right
      align-self-center">
      <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
          {% csrf_token %}
        <button type="submit" class="btn" data-toggle="tooltip"
          data-placement="top" title="Удалить">
          <i class="fas fa-trash-alt"></i>
        </button>
      </form>
    </div>
  </div>
  {% endwith %}
{% empty %}
<div class="align-self-center">
  <span class="text-center font-weight-bold text-muted lead">
    Ваша корзина пуста.
  </span>
</div>
{% endfor %}
<hr>
<div class="total-price-cart">
  <h4 class="row justify-content-center">
    <div class="col-5 col-lg-9 text-right text-grey">
  Итоговая цена:
    </div>
    <div class="col-5 col-lg-2 text-right text-danger">
      ₽{{ cart_total_price|floatformat:2 }}
    </div>
    <div class="col-2 col-lg-1">
    </div>
</h4> </div>

</div>
<hr>
<div class="col-lg-10 mx-auto mb-5">
  <div class="row justify-content-end">
      {% if cart|length > 0 %}
    <div class="col-lg-6 px-0">
      <div class="btn-group d-flex">
        <a href="{% url 'listings:product_list' %}"
          class="btn btn-warning shadow-custom col">
          Вернуться к покупкам
        </a>
        <a href="{% url 'orders:order_create' %}" class="btn btn-danger shadow-custom col">
          Оформить
</a> </div>
    </div>
  </div>
  {% else %}
  <div class="col-lg-3 px-0">
    <div class="btn-group d-flex">
      <a href="{% url 'listings:product_list' %}"
        class="btn btn-warning shadow-custom col">
        Вернуться к покупкам
      </a>
    </div>
</div>
{% endif %}
</div>
</div>
{% endblock content %}