cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

finesauces_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('users.urls')),

    path('', include('listings.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required
from finesauces_project.decorators import user_created_order

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/pdf/',
         staff_member_required(views.invoice_pdf), name='invoice_pdf'),
    path('order/<int:order_id>/pdf/',
         user_created_order(views.invoice_pdf), name='customer_invoice_pdf'),
    path('order/<int:order_id>/',
         user_created_order(views.order_detail), name='order_detail'),
]

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
{% if messages %}
  <div class="shadow-custom messages alert alert-danger 
    col-lg-4 mx-auto text-center">
    {% for message in messages %}
      {{ message }}
      <a href="" class="close">x</a>
    {% endfor %}
  </div>
{% endif %}

<div class="card shadow-custom border-0 col-lg-4 mx-auto mb-3">
  <h3 class="py-2 font-weight-bold text-grey text-center">Войти</h3>
  <form action="" method="post">
    {% csrf_token %}
    <div class="input-field">
      {{ form.email }}
      <label for="email">Электронный адрес</label>
    </div>
    <div class="input-field">
      {{ form.password }}
      <label for="password">Пароль</label>
    </div>
    <button class="btn btn-block btn-warning mb-3" type="submit">
      Войти
    </button>
  </form>
  <div class="text-center mb-2">
    <a href="{% url 'password_reset' %}"
      class="text-decoration-none">
      Забыли свой пароль?
    </a>
  </div>  
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Account{% endblock %}

{% block content %}
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'error' %}
    <div class="shadow-custom messages alert alert-danger text-center
      col-lg-7 mx-auto">
    {% else %}
    <div class="shadow-custom messages alert alert-success text-center
      col-lg-7 mx-auto">
    {% endif %}
      {{ message }}
      <a href="" class="close">x</a>
    </div>
  {% endfor %}
{% endif %}
  <div class="card shadow-custom border-0 col-lg-7 mx-auto mb-3">
    <h2 class="font-weight-bold text-grey mt-2">Профиль</h2>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          <div class="input-field">
            {{ user_form.first_name }}
            <label for="first_name">Имя</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ user_form.last_name }}
            <label for="last_name">Фамилия</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ user_form.email }}
            <label for="email">Электронный адрес</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.phone_number }}
            <label for="phone_number">Номер телефона</label>
          </div>
        </div>
      </div>
      <hr class="mt-0">
      <div class="row">
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.address }}
            <label for="address">Адрес</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.postal_code }}
            <label for="postal_code">Почтовый индекс</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.city }}
            <label for="city">Город</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.country }}
            <label for="country">Страна</label>
          </div>
        </div>
      </div>
      <hr>
      <div class="row">
        <button type="submit" class="btn col" data-toggle="tooltip" 
          data-placement="top"
          title="Введите новые данные и нажмите «Обновить профиль»">
          Обновить профиль</button>
        <a class="btn col" href="{% url 'password_change' %}">
          Изменить пароль
        </a>
      </div>
      <hr>
      <h3 class="mb-3">Ваши заказы:</h3>
      <table class="table">
        {% for order in request.user.orders.all %}
          <tr>
            <td>
              <a href="{{ order.get_absolute_url }}" class="text-decoration-none">
                {{ order.id }}
              </a>
            </td>
            <td>{{ order.created|date }}</td>
            <td class="text-green">
              ₽{{ order.get_total_cost|floatformat:2 }}
            </td>
            <td>
              <a href="{% url 'orders:customer_invoice_pdf' order.id %}" class="text-decoration-none" target="_blank">
                <i class="far fa-file-pdf text-danger"></i>
                Квитанция {{ order.id }}
              </a>
            </td>
            <td>{{ order.status }}</td>
          </tr>
          {% empty %}
          <tr>
            Заказов пока нет
          </tr>
        {% endfor %}
      </table>
    </form>
  </div>
</div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
{% if messages %}
  <div class="shadow-custom messages alert alert-danger 
    col-lg-5 mx-auto text-center">
    {% for message in messages %}
      {{ message }}
        <a href="" class="close">x</a>
      {% endfor %}
  </div>
{% endif %}
<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3">
  <h3 class="py-2 font-weight-bold text-grey text-center">
    Регистрация
  </h3>
  <form action="" method="post">
    <div class="form-group">
      {% csrf_token %}
      <div class="input-field">
        {{ user_form.first_name }}
        <label for="first_name">Имя</label>
      </div>
      <div class="input-field">
        {{ user_form.last_name }}
        <label for="last_name">Фамилия</label>
      </div>
      <div class="input-field">
        {{ user_form.email }}
        <label for="email">Электронный адрес</label>
      </div>
      <div class="input-field">
        {{ user_form.password }}
        <label for="password">Пароль</label>
      </div>
      <div class="input-field">
        {{ user_form.password2 }}
        <label for="password2">Подтвердите пароль</label>
      </div>
    </div>
    <button class="btn btn-block btn-warning mb-3" type="submit">
      Зарегистрироваться
    </button>
  </form>
</div>
{% endblock %}

templates/accounts/register_done.html
{% extends 'base.html' %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3 text-center">
  <h3 class="py-2 font-weight-bold text-grey">
    Добро пожаловать, {{ new_user.first_name }}
  </h3>
  <hr class="my-0">
  <div class="py-2">
    Ваш аккаунт был успешно создан.
    Ты можешь <a href="{% url 'login' %}">войти.</a>
  </div>
</div>
{% endblock %}