cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

finesauces_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('users.urls')),

    path('', include('listings.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('<slug:category_slug>', views.product_list,
         name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', views.product_detail,
         name='product_detail'),
    path('search/', views.search_list, name="search"),
    path('', views.product_list, name='product_list'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Nunito&display=swap"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav
      class="navbar navbar-expand-md navbar-dark bg-danger fixed-top py-1"
      id="main-nav"
    >
      <div class="container">
        <a href="{% url 'listings:product_list' %}" class="navbar-brand">
          <h3 class="font-weight-bold">UMARSTORE</h3>
        </a>
        <button class="navbar-toggler" data-toggle="collapse" 
          data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a href="{% url 'profile' %}" class="nav-link text-white">
                  <i class="fas fa-user"></i> {{ request.user.email }}
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link text-white">
                  <i class="fas fa-sign-out-alt"></i> Выйти
                </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a href="{% url 'login' %}" class="nav-link text-white">
                  <i class="fas fa-sign-in-alt"></i> Войти
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'register' %}" class="nav-link text-white">
                  <i class="fas fa-user-plus"></i> Регистрация
                </a>
              </li>
            {% endif %}
            <li class="nav-item">
              <form action="{% url 'listings:search' %}" method="POST">
                {% csrf_token %}
                        <input name="keywords" type="search" placeholder="Anywords" aria-label="search">
                        <button type="submit">
                          <i class="fas fa-search"></i>
                        </button>
              </form>
            </li>
            <li class="nav-item">
              <div class="dropdown-custom">
                <a href="{% url 'cart:cart_detail' %}" 
                  class="nav-link text-white drop-btn">
                  <i class="fas fa-shopping-cart"></i>
                  ₽<span id="cart_price">{{ cart_total_price|floatformat:2 }}</span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container py-5">{% block content %} {% endblock content %}</div>
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
      integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
      crossorigin="anonymous"
    ></script>
    <script src=" {% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
    

      function ini() {
        const content = document.getElementById("seasonsContent")
        const childs = Array.from(content.children)
        const inputs = childs.map(i => i.children[0].children[0])
        console.log(inputs)
        const url = window.location.href
        const query = url.split('?').length > 1 ? url.split("?")[1].split("&") : []
        query.forEach(i => {
          const el = i.split('=')
          console.log("dfdfdf", el)
          if (el.length > 1) {
            const item = inputs.find(k => k.value === el[1] && 'season' === el[0])
            if (item) item.checked = true
          }
        })
      }
      // setTimeout(() => {
        ini()
      // }, 1000)
      // function fetchSeasonData(e, name, id){
      //   let url = window.location.href
      //   if (url.search("\\?") > -1) {
      //     if (e.target.checked) {
      //       window.location.href = window.location.href + '&'+name+'='+id
      //     } else {
      //       const res = window.location.href.search(name+'='+id)
      //       if (res > -1) {
      //         const s = name+'='+id
      //         if (url[res - 1] === '&') url = url.split('').filter((i, ind) => ind !== res - 1).join("")
      //         else url = url.split('').filter((i, ind) => ind !== res + s.length).join("")
      //       } 
      //       window.location.href = url.replace(name+'='+id, '')
      //     }
      //   } else window.location.href = window.location.href + '?'+name+'='+id
      // }



    function init_one() {
        const content = document.getElementById("brandsContent")
        const childs = Array.from(content.children)
        const inputs = childs.map(i => i.children[0].children[0])
        console.log(inputs)
        const url = window.location.href
        const query = url.split('?').length > 1 ? url.split("?")[1].split("&") : []
        query.forEach(i => {
          const el = i.split('=')
          if (el.length > 1) {
            const item = inputs.find(k => k.value === el[1])
            if (item) item.checked = true
          }
        })
      }
      // setTimeout(() => {
        init_one()
      // }, 1000)
      // function fetchBrandData(e, name, id){
      //   let url = window.location.href
      //   if (url.search("\\?") > -1) {
      //     if (e.target.checked) {
      //       window.location.href = window.location.href + '&'+name+'='+id
      //     } else {
      //       const res = window.location.href.search(name+'='+id)
      //       if (res > -1) {
      //         const s = name+'='+id
      //         if (url[res - 1] === '&') url = url.split('').filter((i, ind) => ind !== res - 1).join("")
      //         else url = url.split('').filter((i, ind) => ind !== res + s.length).join("")
      //       } 
      //       window.location.href = url.replace(name+'='+id, '')
      //     }
      //   } else window.location.href = window.location.href + '?'+name+'='+id
      // }
    


      function init() {
        const content = document.getElementById("colorsContent")
        const childs = Array.from(content.children)
        const inputs = childs.map(i => i.children[0].children[0])
        console.log(inputs)
        const url = window.location.href
        const query = url.split('?').length > 1 ? url.split("?")[1].split("&") : []
        query.forEach(i => {
          const el = i.split('=')
          if (el.length > 1) {
            const item = inputs.find(k => k.value === el[1] && 'color' === el[0])
            if (item) item.checked = true
          }
        })
      }
      // setTimeout(() => {
        init()
      // }, 1000)
      function fetchData(e, name, id){
        let url = window.location.href
        if (url.search("\\?") > -1) {
          if (e.target.checked) {
            window.location.href = window.location.href + '&'+name+'='+id
          } else {
            const res = window.location.href.search(name+'='+id)
            if (res > -1) {
              const s = name+'='+id
              if (url[res - 1] === '&') url = url.split('').filter((i, ind) => ind !== res - 1).join("")
              else url = url.split('').filter((i, ind) => ind !== res + s.length).join("")
            } 
            window.location.href = url.replace(name+'='+id, '')
          }
        } else window.location.href = window.location.href + '?'+name+'='+id
      }
    </script>
  </body>
</html>